spring.application.name=onboarding-clientes
server.port=8081

# Conexión JDBC a PostgreSQL Local
spring.datasource.url=jdbc:postgresql://localhost:5433/onboarding
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# Dialecto JPA e Hibernate para PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Desactivar consola H2 cuando se utiliza PostgreSQL
spring.h2.console.enabled=false

# Documentación Swagger / OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# Logging
logging.level.com.kapm.onboarding_clientes=DEBUG
logging.level.org.hibernate.SQL=DEBUG
